@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR

package Logic <<Rectangle>>{
interface Command <<Interface>>
interface Parser <<Interface>>

class AssignCommand
class AssignCommandParser
class Index
class DurationSupporter
class Duration

AssignCommand .up.|> Command
AssignCommandParser .up.|> Parser
AssignCommandParser -right- AssignCommand
AssignCommand -right-> "1" Index: contains >
AssignCommand -down-> "1" DurationSupporter: contains >
DurationSupporter -left-> "1" Duration: contains >
}
@enduml
