@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

PatientBook *--> "1" UniquePatientList
PatientBook *--> "1" UniqueTagList

UniqueTagList -[hidden]right- UniquePatientList

UniqueTagList *--> "*" Tag
UniquePatientList o--> Patient

Patient -up-> "*" Tag

Patient *--> Name
Patient *--> Phone
Patient *--> Nric
Patient *--> Address
Patient *--> Remark

AppointmentBook *--> "1" UniqueAppointmentList

UniqueAppointmentList o--> Appointment

Appointment *--> Date
Appointment *--> "2" Time
Appointment --> Patient
@enduml
