@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NuudleParser" as NuudleParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "cmd:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> NuudleParser : parseCommand("delete 1")
activate NuudleParser

create DeleteCommandParser
NuudleParser -> DeleteCommandParser : new
activate DeleteCommandParser

DeleteCommandParser --> NuudleParser
deactivate DeleteCommandParser

NuudleParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand : new
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : cmd
deactivate DeleteCommand

DeleteCommandParser --> NuudleParser : cmd
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> NuudleParser
destroy DeleteCommandParser

NuudleParser --> LogicManager : cmd
deactivate NuudleParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : getFilteredPatientList()
activate Model

Model --> DeleteCommand : lastShownList
deactivate Model

DeleteCommand -> Model : deletePatient(patientToDelete)
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : deleteAppointmentsWithPatient(patientToDelete)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult: new
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
