@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyPatientBook <<Interface>>
Interface ReadOnlyAppointmentBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class PatientBook
Class AppointmentBook
Class ReadOnlyPatientBook
Class ReadOnlyAppointmentBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Patient {
Class Patient
Class Address
Class Nric
Class Remark
Class Name
Class Phone
Class UniquePatientList
}

Package Appointment {
Class Appointment
Class Date
Class Time
Class UniqueAppointmentList
}

Package Tag {
Class Tag
}
}

Class HiddenOutside #FFFFFF
HiddenOutside .down.> Model

PatientBook .left.|> ReadOnlyPatientBook
AppointmentBook .right.|> ReadOnlyAppointmentBook

ModelManager .right.|> Model
Model .right.> ObservableList
ModelManager o--> "1" PatientBook
ModelManager o--> "1" AppointmentBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .left.|> ReadOnlyUserPrefs

PatientBook *--> "1" UniquePatientList
UniquePatientList o--> "*" Patient
Patient *--> Name
Patient *--> Phone
Patient *--> Nric
Patient *--> Remark
Patient *--> Address
Patient *--> "*" Tag

AppointmentBook *--> "1" UniqueAppointmentList
UniqueAppointmentList o--> "*" Appointment
UniqueAppointmentList -[hidden]down-> Appointment
Appointment *--> Date
Appointment *--> "2" Time
Appointment *--> Patient

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address


ModelManager -->"1" Patient : filtered list
ModelManager -->"1" Appointment : filtered list
@enduml
