@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface PatientBookStorage <<Interface>>
Interface AppointmentBookStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonPatientBookStorage
Class JsonAppointmentBookStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> PatientBookStorage
StorageManager o--> AppointmentBookStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonPatientBookStorage .left.|> PatientBookStorage
JsonPatientBookStorage .down.> JsonSerializablePatientBook
JsonAppointmentBookStorage .right.|> AppointmentBookStorage
JsonAppointmentBookStorage .down.> JsonSerializableAppointmentBook
JsonSerializablePatientBook .right.> JsonAdaptedPatient
JsonAdaptedPatient .up.> JsonAdaptedTag
JsonSerializableAppointmentBook .right.> JsonAdaptedAppointment
@enduml
