@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "clear"

package States <<rectangle>> {
    package State3 {
            class State3.1 as "__pb2:PatientBook__"
            class State3.2 as "__ab2:AppointmentBook__"
    }

    package State2 {
            class State2.1 as "__pb1:PatientBook__"
            class State2.2 as "__ab1:AppointmentBook__"
    }

    package State1 {
        class State1.1 as "__pb0:PatientBook__"
        class State1.2 as "__ab0:AppointmentBook__"
    }
}
State1.2 -[hidden]right-> State2.1
State2.2 -[hidden]right-> State3.1

class Pointer as "Current State" #FFFFF
Pointer -[hidden]up-> State3
Pointer -up-> State3
note right on link: State ab2, pb2 deleted.
@end
